In [ ]:
#1.Create a pandas dataframe (DataFrame name as 'df') with numpy random values (4 features and 4 observation)

import numpy as np
import pandas as pd

s1 = np.random.rand(4)
s2 = np.random.rand(4)
s3 = np.random.rand(4)
s4 = np.random.rand(4)

df = pd.DataFrame([s1,s2,s3,s4])
df

          0         1         2         3
0  0.624207  0.589748  0.425301  0.200985
1  0.957014  0.874764  0.309385  0.636246
2  0.860036  0.899038  0.324309  0.984639
3  0.925173  0.100629  0.247323  0.189286

In [ ]:
#2.Rename the task - 1 'df' dataframe column names to 'Random value 1', 'Random value 2', 'Random value 3' & 'Random value 4'

df.columns = ['Random value 1','Random value 2','Random value 3','Random value 4']
df

   Random value 1  Random value 2  Random value 3  Random value 4
0        0.624207        0.589748        0.425301        0.200985
1        0.957014        0.874764        0.309385        0.636246
2        0.860036        0.899038        0.324309        0.984639
3        0.925173        0.100629        0.247323        0.189286

In [ ]:
#3.Find the descriptive statistics of the 'df' dataframe.

df.describe()

       Random value 1  Random value 2  Random value 3  Random value 4
count        4.000000        4.000000        4.000000        4.000000
mean         0.841608        0.616045        0.326580        0.502789
std          0.150449        0.371199        0.073775        0.382692
min          0.624207        0.100629        0.247323        0.189286
25%          0.801079        0.467468        0.293870        0.198060
50%          0.892605        0.732256        0.316847        0.418615
75%          0.933133        0.880833        0.349557        0.723344
max          0.957014        0.899038        0.425301        0.984639

In [ ]:
#4.Check for the null values in 'df' and find the data type of the columns.

df.isnull()

   Random value 1  Random value 2  Random value 3  Random value 4
0           False           False           False           False
1           False           False           False           False
2           False           False           False           False
3           False           False           False           False

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Random value 1  4 non-null      float64
 1   Random value 2  4 non-null      float64
 2   Random value 3  4 non-null      float64
 3   Random value 4  4 non-null      float64
dtypes: float64(4)
memory usage: 256.0 bytes

In [ ]:
df['Random value 1'].dtype
df['Random value 2'].dtype
df['Random value 3'].dtype
df['Random value 4'].dtype

dtype('float64')

In [ ]:
#5.Display the 'Random value 2' & 'Random value 3' columns with location method and index location method.

df.loc[0:,'Random value 2':'Random value 3']

   Random value 2  Random value 3
0        0.589748        0.425301
1        0.874764        0.309385
2        0.899038        0.324309
3        0.100629        0.247323

In [ ]:
df.iloc[0:,1:3]

   Random value 2  Random value 3
0        0.589748        0.425301
1        0.874764        0.309385
2        0.899038        0.324309
3        0.100629        0.247323