In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

**Task 1: Read the dataset and do data pre-processing**

In [2]:
df = pd.read_csv("/content/drug200.csv")
df.head()

   Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  DrugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  DrugY

In [3]:
df.tail()

     Age Sex      BP Cholesterol  Na_to_K   Drug
195   56   F     LOW        HIGH   11.567  drugC
196   16   M     LOW        HIGH   12.006  drugC
197   52   M  NORMAL        HIGH    9.894  drugX
198   23   M  NORMAL      NORMAL   14.020  drugX
199   40   F     LOW      NORMAL   11.349  drugX

In [4]:
df.shape

(200, 6)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Age          200 non-null    int64
 1   Sex          200 non-null    object
 2   BP           200 non-null    object
 3   Cholesterol  200 non-null    object
 4   Na_to_K      200 non-null    float64
 5   Drug         200 non-null    object
dtypes: float64(1), int64(1), object(4)
memory usage: 9.5+ KB

In [6]:
df.isnull().any

<bound method NDFrame._add_numeric_operations.<locals>.any of        Age    Sex     BP  Cholesterol  Na_to_K   Drug
0    False  False  False        False    False  False
1    False  False  False        False    False  False
2    False  False  False        False    False  False
3    False  False  False        False    False  False
4    False  False  False        False    False  False
..     ...    ...    ...          ...      ...    ...
195  False  False  False        False    False  False
196  False  False  False        False    False  False
197  False  False  False        False    False  False
198  False  False  False        False    False  False
199  False  False  False        False    False  False

[200 rows x 6 columns]>

In [7]:
df.isnull().sum()

Age            0
Sex            0
BP             0
Cholesterol    0
Na_to_K        0
Drug           0
dtype: int64

In [8]:
df.describe()

              Age     Na_to_K
count  200.000000  200.000000
mean    44.315000   16.084485
std     16.544315    7.223956
min     15.000000    6.269000
25%     31.000000   10.445500
50%     45.000000   13.936500
75%     58.000000   19.380000
max     74.000000   38.247000

**Task 1: Data Preprocessing**

In [9]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler

In [10]:
label_encoder = LabelEncoder()
df['Sex'] = label_encoder.fit_transform(df['Sex'])
df['BP'] = label_encoder.fit_transform(df['BP'])
df['Cholesterol'] = label_encoder.fit_transform(df['Cholesterol'])
df['Drug'] = label_encoder.fit_transform(df['Drug'])

In [11]:
print('Sex : ',df['Sex'],'\n')
print('BP : \n',df['BP'],'\n')
print('Cholesterol : \n',df['Cholesterol'],'\n')
print('Drug : \n',df['Drug'],'\n')

Sex :  0      0
1      1
2      1
3      0
4      0
      ..
195    0
196    1
197    1
198    1
199    0
Name: Sex, Length: 200, dtype: int64

BP :
 0      0
1      1
2      1
3      2
4      1
      ..
195    1
196    1
197    2
198    2
199    1
Name: BP, Length: 200, dtype: int64

Cholesterol :
 0      0
1      0
2      0
3      0
4      0
      ..
195    0
196    0
197    0
198    1
199    1
Name: Cholesterol, Length: 200, dtype: int64

Drug :
 0      0
1      3
2      3
3      4
4      0
      ..
195    3
196    3
197    4
198    4
199    4
Name: Drug, Length: 200, dtype: int64

In [12]:
x=df.drop('Drug', axis=1)
y=df['Drug']

In [13]:
df

     Age  Sex  BP  Cholesterol  Na_to_K  Drug
0     23    0   0            0   25.355     0
1     47    1   1            0   13.093     3
2     47    1   1            0   10.114     3
3     28    0   2            0    7.798     4
4     61    0   1            0   18.043     0
..   ...  ...  ..          ...      ...   ...
195   56    0   1            0   11.567     3
196   16    1   1            0   12.006     3
197   52    1   2            0    9.894     4
198   23    1   2            1   14.020     4
199   40    0   1            1   11.349     4

[200 rows x 6 columns]

In [14]:
x.shape,y.shape

((200, 5), (200,))

In [15]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.2, random_state=10)

In [16]:
xtrain.shape, xtest.shape

((160, 5), (40, 5))

In [17]:
ytrain.shape, ytest.shape

((160,), (40,))

**Task 2: Building an ANN Model**

In [18]:
#pip install keras
#ip install tensorflow

In [19]:
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [20]:
model = keras.Sequential()
model.add(Dense(64, activation="relu", input_shape =(xtrain.shape[1],)))
model.add(layers.Dense(32, activation="relu"))
model.add(layers.Dense(16, activation="relu"))
model.add(layers.Dense(8, activation="relu"))
model.add(layers.Dense(5, activation="softmax"))

In [21]:
x=df.iloc[:,0:5]
y=df.iloc[:,5:]
x, y

(     Age  Sex  BP  Cholesterol  Na_to_K
 0     23    0   0            0   25.355
 1     47    1   1            0   13.093
 2     47    1   1            0   10.114
 3     28    0   2            0    7.798
 4     61    0   1            0   18.043
 ..   ...  ...  ..          ...      ...
 195   56    0   1            0   11.567
 196   16    1   1            0   12.006
 197   52    1   2            0    9.894
 198   23    1   2            1   14.020
 199   40    0   1            1   11.349

 [200 rows x 5 columns],
      Drug
 0       0
 1       3
 2       3
 3       4
 4       0
 ..    ...
 195     3
 196     3
 197     4
 198     4
 199     4

 [200 rows x 1 columns])

In [22]:
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [23]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 64)                384

 dense_1 (Dense)             (None, 32)                2080

 dense_2 (Dense)             (None, 16)                528

 dense_3 (Dense)             (None, 8)                 136

 dense_4 (Dense)             (None, 5)                 45

=================================================================
Total params: 3,173
Trainable params: 3,173
Non-trainable params: 0
_________________________________________________________________

In [24]:
#Train the model

In [25]:
ytrain_encoded = label_encoder.fit_transform(ytrain)
ytest_encoded = label_encoder.transform(ytest)

In [26]:
model.fit(xtrain,ytrain,epochs=20, batch_size=16, validation_data=(xtest,ytest))

Epoch 1/20
10/10 [==============================] - 2s 32ms/step - loss: 3.4692 - accuracy: 0.3000 - val_loss: 1.5269 - val_accuracy: 0.5000
Epoch 2/20
10/10 [==============================] - 0s 8ms/step - loss: 1.5995 - accuracy: 0.4688 - val_loss: 1.5355 - val_accuracy: 0.4000
Epoch 3/20
10/10 [==============================] - 0s 6ms/step - loss: 1.4679 - accuracy: 0.5625 - val_loss: 1.4653 - val_accuracy: 0.4500
Epoch 4/20
10/10 [==============================] - 0s 6ms/step - loss: 1.3531 - accuracy: 0.5875 - val_loss: 1.3927 - val_accuracy: 0.4500
Epoch 5/20
10/10 [==============================] - 0s 8ms/step - loss: 1.2827 - accuracy: 0.5750 - val_loss: 1.3532 - val_accuracy: 0.4750
Epoch 6/20
10/10 [==============================] - 0s 6ms/step - loss: 1.2163 - accuracy: 0.6062 - val_loss: 1.3051 - val_accuracy: 0.5000
Epoch 7/20
10/10 [==============================] - 0s 6ms/step - loss: 1.1624 - accuracy: 0.6125 - val_loss: 1.2818 - val_accuracy: 0.5000
Epoch 8/20
10/10 [==============================] - 0s 6ms/step - loss: 1.1199 - accuracy: 0.6000 - val_loss: 1.2566 - val_accuracy: 0.5000
Epoch 9/20
10/10 [==============================] - 0s 6ms/step - loss: 1.0777 - accuracy: 0.6000 - val_loss: 1.2322 - val_accuracy: 0.4750
Epoch 10/20
10/10 [==============================] - 0s 6ms/step - loss: 1.0450 - accuracy: 0.6062 - val_loss: 1.2137 - val_accuracy: 0.4750
Epoch 11/20
10/10 [==============================] - 0s 8ms/step - loss: 1.0104 - accuracy: 0.6125 - val_loss: 1.2166 - val_accuracy: 0.5000
Epoch 12/20
10/10 [==============================] - 0s 8ms/step - loss: 0.9804 - accuracy: 0.6125 - val_loss: 1.2308 - val_accuracy: 0.5000
Epoch 13/20
10/10 [==============================] - 0s 8ms/step - loss: 0.9659 - accuracy: 0.6125 - val_loss: 1.2252 - val_accuracy: 0.5000
Epoch 14/20
10/10 [==============================] - 0s 6ms/step - loss: 0.9483 - accuracy: 0.6250 - val_loss: 1.2299 - val_accuracy: 0.5000
Epoch 15/20
10/10 [==============================] - 0s 8ms/step - loss: 0.9336 - accuracy: 0.6125 - val_loss: 1.1774 - val_accuracy: 0.5000
Epoch 16/20
10/10 [==============================] - 0s 6ms/step - loss: 0.9376 - accuracy: 0.6250 - val_loss: 1.1781 - val_accuracy: 0.5000
Epoch 17/20
10/10 [==============================] - 0s 8ms/step - loss: 0.9309 - accuracy: 0.6187 - val_loss: 1.2735 - val_accuracy: 0.5000
Epoch 18/20
10/10 [==============================] - 0s 8ms/step - loss: 0.9504 - accuracy: 0.6187 - val_loss: 1.1437 - val_accuracy: 0.5000
Epoch 19/20
10/10 [==============================] - 0s 7ms/step - loss: 0.9014 - accuracy: 0.6187 - val_loss: 1.2000 - val_accuracy: 0.5000
Epoch 20/20
10/10 [==============================] - 0s 8ms/step - loss: 0.8895 - accuracy: 0.6313 - val_loss: 1.1678 - val_accuracy: 0.5000

In [27]:
model

In [28]:
ypred = model.predict(xtest)
ypred

2/2 [==============================] - 0s 4ms/step

array([[8.89063835e-01, 2.36197822e-02, 6.88375731e-04, 3.88187245e-02,
        4.78093810e-02],
       [3.66582990e-01, 1.04136460e-01, 2.85621043e-02, 1.02139585e-01,
        3.98578823e-01],
       [4.14020061e-01, 1.71278939e-01, 7.08532427e-03, 7.60913566e-02,
        3.31524312e-01],
       [6.14862800e-01, 4.27593701e-02, 4.39838925e-03, 6.74772933e-02,
        2.70502150e-01],
       [8.52034330e-01, 2.43673362e-02, 1.25224091e-04, 2.56112535e-02,
        9.78617445e-02],
       [9.94101107e-01, 4.97012108e-04, 9.45039574e-06, 2.98709376e-03,
        2.40527606e-03],
       [2.23135829e-01, 1.66830063e-01, 3.31607386e-02, 8.19960758e-02,
        4.94877249e-01],
       [7.18844593e-01, 4.85854372e-02, 3.66329867e-03, 7.19396621e-02,
        1.56967029e-01],
       [9.96804178e-01, 2.29176949e-04, 1.02249169e-05, 1.53721101e-03,
        1.41918589e-03],
       [1.36978224e-01, 1.63420767e-01, 1.94977328e-01, 1.21692270e-01,
        3.82931501e-01],
       [9.99916375e-01, 2.51608685e-06, 3.53221417e-08, 5.08992816e-05,
        3.01704913e-05],
       [2.17329070e-01, 1.85821548e-01, 8.32739845e-02, 1.17965758e-01,
        3.95609647e-01],
       [9.67196047e-01, 3.16046248e-03, 1.28150743e-04, 1.17980503e-02,
        1.77174192e-02],
       [8.89874101e-02, 1.27989620e-01, 1.87502652e-01, 1.22876205e-01,
        4.72644150e-01],
       [1.63577557e-01, 1.75232992e-01, 1.51695773e-01, 1.30200893e-01,
        3.79292697e-01],
       [1.13026895e-01, 1.50352448e-01, 1.84069708e-01, 1.09663360e-01,
        4.42887545e-01],
       [8.78939450e-01, 1.29320966e-02, 8.54540558e-04, 3.26527767e-02,
        7.46211633e-02],
       [8.70428205e-01, 2.48287041e-02, 2.88352603e-03, 5.07982410e-02,
        5.10611162e-02],
       [9.27730128e-02, 1.34473279e-01, 1.66453183e-01, 8.89501572e-02,
        5.17350376e-01],
       [8.22047949e-01, 1.68274939e-02, 1.36886054e-04, 2.28971187e-02,
        1.38090521e-01],
       [6.44729197e-01, 6.39274418e-02, 3.11955507e-03, 6.83874264e-02,
        2.19836354e-01],
       [3.34388554e-01, 1.62285328e-01, 8.31436366e-03, 6.66822717e-02,
        4.28329468e-01],
       [3.64832848e-01, 1.91950247e-01, 4.01106067e-02, 1.36100978e-01,
        2.67005354e-01],
       [1.38860285e-01, 1.62078261e-01, 1.47923946e-01, 1.11882299e-01,
        4.39255208e-01],
       [6.14587784e-01, 7.43864551e-02, 6.43295189e-03, 8.79394934e-02,
        2.16653302e-01],
       [9.74736691e-01, 3.17235687e-03, 3.13659548e-04, 1.14479857e-02,
        1.03292437e-02],
       [1.38505235e-01, 1.67155713e-01, 2.02924013e-01, 1.41125321e-01,
        3.50289643e-01],
       [2.70651102e-01, 1.92468941e-01, 5.15338853e-02, 1.16458431e-01,
        3.68887633e-01],
       [8.35737064e-02, 1.32140487e-01, 1.70119941e-01, 1.01230294e-01,
        5.12935579e-01],
       [6.00436389e-01, 4.57576886e-02, 2.42685573e-03, 5.37486225e-02,
        2.97630489e-01],
       [4.28226173e-01, 1.22273386e-01, 1.43391499e-02, 9.34448168e-02,
        3.41716439e-01],
       [4.85020489e-01, 8.10322165e-02, 1.94262527e-02, 1.06646545e-01,
        3.07874471e-01],
       [3.51808995e-01, 2.04606518e-01, 4.19086516e-02, 1.36694908e-01,
        2.64980853e-01],
       [4.54413503e-01, 1.88199714e-01, 1.22146141e-02, 1.04707152e-01,
        2.40465075e-01],
       [9.39705074e-02, 1.35336414e-01, 1.67261958e-01, 8.96079838e-02,
        5.13823152e-01],
       [5.71305394e-01, 7.33973309e-02, 4.14256006e-03, 6.87165558e-02,
        2.82438070e-01],
       [1.09414004e-01, 1.42988145e-01, 1.62656739e-01, 8.82487521e-02,
        4.96692270e-01],
       [7.05901086e-01, 6.80266991e-02, 9.08054318e-03, 9.45426226e-02,
        1.22448981e-01],
       [4.50905442e-01, 1.94289416e-01, 1.63970832e-02, 1.17797889e-01,
        2.20610157e-01],
       [2.99955755e-01, 1.99707627e-01, 5.13112284e-02, 1.28506064e-01,
        3.20519388e-01]], dtype=float32)

In [29]:
loss, accuracy = model.evaluate(xtest, ytest)
print(f"Test Loss: {loss:.4f}")
print(f"Test Accuracy: {accuracy:.4f}")

2/2 [==============================] - 0s 10ms/step - loss: 1.1678 - accuracy: 0.5000
Test Loss: 1.1678
Test Accuracy: 0.5000

**Task 3: Test the model with random data**

In [31]:
import numpy as np
random_sample = np.array([[40, 0, 1, 1, 15]])
predictions = model.predict(random_sample)
predicted_class = label_encoder.inverse_transform(np.argmax(predictions, axis=1))
print("Predicted Drug Class:", predicted_class)

1/1 [==============================] - 0s 92ms/step
Predicted Drug Class: [0]

In [32]:
ypred = model.predict([[40, 0, 1, 1, 15]])
ypred

1/1 [==============================] - 0s 37ms/step

array([[0.46453828, 0.11864559, 0.00900595, 0.08394153, 0.32386857]],
      dtype=float32)

In [33]:
ypred= np.argmax(ypred)

In [34]:
ypred

0

In [35]:
comp = pd.DataFrame(ytest)
comp.columns = ['Actual Value']
comp['Predicted values'] = ypred
comp

     Actual Value  Predicted values
59              0                 0
5               4                 0
20              0                 0
198             4                 0
52              0                 0
19              0                 0
162             4                 0
55              3                 0
69              0                 0
2               3                 0
98              0                 0
10              3                 0
75              0                 0
142             2                 0
124             2                 0
63              4                 0
109             0                 0
78              1                 0
111             4                 0
185             0                 0
154             0                 0
130             0                 0
61              1                 0
87              0                 0
102             3                 0
121             0                 0
136             2                 0
1               3                 0
47              3                 0
172             0                 0
159             4                 0
39              4                 0
76              1                 0
91              0                 0
35              4                 0
178             0                 0
127             4                 0
169             1                 0
46              1                 0
174             1                 0